### ISSUE TITLE
Allow upload from raw yaml metadata files

### ISSUE THREAD

**Issue by merrygoat** [LightForm-group/datalight#16]
Allow upload of records using raw yaml files from the command line (as an alternative to the beautiful UI that I spent a huge amount of time working on) for people that like to make things hard for themselves.

**Comment by aplowman** [comment]
Just a suggestion: not sure if you've heard of this one, but [click](https://click.palletsprojects.com/en/7.x/) is a great package for easily creating CLIs.

**Comment by merrygoat** [comment]
Thank you, i'll have a look at that.
