### ISSUE TITLE
Experimental UI forms should be downloaded from the wiki

### ISSUE THREAD

**Issue by merrygoat** [LightForm-group/datalight#9]
UI descriptions should be downloaded from the lightform wiki. Since all of the yamls are located in a single folder, the folder can just be scraped off github and each file used to populate an entry in the experimental list.

**Comment by aplowman** [comment]
Something [like this](https://sookocheff.com/post/tools/downloading-directories-of-code-from-github-using-the-github-api/) might be appropriate here. Perhaps we could ask users to add some environment variables for GitHub credentials. Or, a prompt could probably be included in the `setup.py` installation script that sets these environment variables (if you end up packaging the code).

**Comment by aplowman** [comment]
Possibly simpler solution: https://minhaskamal.github.io/DownGit/#/home

**Comment by merrygoat** [comment]
Fixed in 1e2a867922cb5491c7e653bdb533d962156b42f3.
